export const STANDARD_COLUMNS = [
    { name: 'id', label: 'ShipmentID' },
    { name: 'origin', label: 'OriginCountry' },
    { name: 'destination', label: 'DestinationCountry' },
    { name: 'shipper', label: 'ShipperName' },
    { name: 'agent', label: 'AgentName' },
    { name: 'pod', label: 'Proof of Delivery' },
    { name: 'gp20', label: "20'GP" },
    { name: 'gp40', label: "40'GP" },
    { name: 'rate', label: 'Rate' },
    { name: 'carrier', label: 'Carrier' },
    { name: 'type', label: 'Type' },
    { name: 'remark1', label: 'Remark1' },
    { name: 'remark2', label: 'Remark2' },
    { name: 'remark3', label: 'Remark3' },
    { name: 'transit_time', label: 'Date-time' },
  ];